apply plugin: 'com.android.library'

android {
    compileSdkVersion 34
    namespace = "com.termux.view"

    defaultConfig {
        minSdkVersion 26
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    api project(":terminal-emulator")
    implementation "androidx.annotation:annotation:1.7.0"
    testImplementation "junit:junit:4.13.2"
}
